baseurl: "http://127.0.0.1:3857"
title: "V Congreso Modelización Forestal"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "VI Reunión del Grupo de Modelización Forestal"
  Description: "Conference description"
  Date: "7 y 8 de Noviembre de 2019"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "Centre de Ciència i  Tecnologia Forestal de Catalunya (CTFC)"
  Address: "Ctra. Sant Llorenç km.2\n Solsona (Lleida)"
  City:  "Solsona"
  State: "Lleida"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - schedule
    - speakers
    #- partners
    - comitee
    - inscription
    #- contact
    - sponsors


  # Titles which you can translate to other languages
  Titles:
    about: "La reunión"
    location: "Sede"
    speakers: "Ponentes"
    schedule: "Programa"
    sponsors: "Colaboradores"
    partners: "Partners"
    contact: "Contacto"
    comitee: "Comité Organizador y científico"
    comitee1: "Comité Organizador"
    comitee2: "Comité Científico"
    inscription: "Inscripción y documentación"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Inscríbete ya!"
    link: "http://register.example.com"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
#  ForkButton:
#    repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "CTFC"
      logo: "/img/logo_ctfc.jpg"
      url: "https://ctfc.cat"
    - name: "SECF"
      logo: "/img/logo_secf.jpg"
      url: "https://secforestales.org"

    - name: "UdL"
      logo: "/img/logo_udl.jpg"
      url: "https://udl.cat"

  # List of Partners
  Partners:
    - name: "Hugo"
      logo: "/img/hugo.jpg"
      url: "https://gohugo.io"
    - name: "BrazilJS"
      logo: "/img/partner.png"
      url: "http://braziljs.org"

  # The entire schedule
  Schedule:
    - name: "Check-in / Breakfast"
      time: "9h00"
    
    
    - name: "Modelización de la Ecofisiología"
      time: "9h30"
      

    - name: "Miquel de Cáceres"
      company: "CTFC"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      link:
        href: "http://twitter.com/linus"
        text: "@linus"
      presentation:
        title: "Digging into a Linux Kernel"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "10h00"

    - name: "Bill Gates"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Microsoft"
      link:
        href: "http://github.com/billy95"
        text: "@billy95"
      presentation:
        title: "Introducing Windows 12"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "11h00"

    - name: "Lunch"
      time: "12h00"

    - name: "Chuck Norris"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Delta Command"
      link:
        href: "http://twitter.com/littlechuck"
        text: "@littlechuck"
      presentation:
        title: "How to kill a elephant with one finger"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "13h00"

    - name: "Steve Jobs"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Apple, Inc."
      link:
        href: "http://github.com/stevie"
        text: "@stevie"
      presentation:
        title: "Presenting iPad"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "14h00"

    - name: "Coffee-break"
      time: "15h00"

    - name: "Mark Zuckerberg"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Facebook"
      link:
        href: "http://twitter.com/zuck"
        text: "@zuck"
      presentation:
        title: "Revealing Facebook Secrets"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "16h00"

    - name: "Steve Wozniak"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Apple, Inc."
      link:
        href: "http://twitter.com/woz"
        text: "@woz"
      presentation:
        title: "Why do I prefer Android over iPhone"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "17h00"


# The entire schedule
  comitee:
    - name: "Aitor Ameztegui"
      photo: "/img/Aitor_Foto.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, s"
      company: "Universitat de Lleida"
      link:
        href: "http://twitter.com/zuck"
        text: "@zuck"
        
    - name: "Andrés Bravo-Oviedo"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, s"
      company: "CSIC - Museo de Ciencias Naturales"
      link:
        href: "http://twitter.com/zuck"
        text: "@zuck"
        
    - name: "Cristina Vega"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, s"
      company: "Universitat de Lleida"
      link:
        href: "http://twitter.com/zuck"
        text: "@zuck"
        
    - name: "Antoni Trasobares"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, s"
      company: "Centre de Ciència i Tecnologia de Catalunya"
      link:
        href: "http://twitter.com/zuck"
        text: "@zuck"
        
    - name: "Assu Planas"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, s"
      company: "Centre de Ciència i Tecnologia de Catalunya"
      link:
        href: "http://twitter.com/zuck"
        text: "@zuck"
comitee2:
    - name: "Andrés Bravo-Oviedo"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, s"
      company: "CSIC - Museo de Ciencias Naturales"
      link:
        href: "http://twitter.com/zuck"
        text: "@zuck"
        
    - name: "Cristina Vega"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, s"
      company: "Universitat de Lleida"
      link:
        href: "http://twitter.com/zuck"
        text: "@zuck"
        
    - name: "Antoni Trasobares"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, s"
      company: "Centre de Ciència i Tecnologia de Catalunya"
      link:
        href: "http://twitter.com/zuck"
        text: "@zuck"
        
    - name: "Assu Planas"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, s"
      company: "Centre de Ciència i Tecnologia de Catalunya"
      link:
        href: "http://twitter.com/zuck"
        text: "@zuck"